### ISSUE TITLE
map-get within a map-get gives wrong output

### ISSUE THREAD

**Issue by denniscohn** [Scrum/postcss-map-get#13]
We have a colorset defined in our css file.
`
$colorset: theme-a !default;
$colorsets: (
  theme-a: (
    secondary-color: $green-100,
    contrast-color: $white-100,
    color-text: $black-100,
  ),
  theme-b: (
    secondary-color: $white-100,
    contrast-color: $green-100,
    color-text: $dark-grey-100,
  ),
 ....
)`

Then we are getting the $color-sec per theme by the following variable.

`$color-sec:                     map-get($theme-colors, secondary-color);`

The code above works perfectly in scss but i'm trying to use postcss instead of sass.
When I look at my output, I see the folowing code:

`background-color: map-get(map-get((
  corporate: (
    secondary-color: #0C8066,
    contrast-color: #FFFFFF,
    color-text: #0C8066,
  ),
  ea: (
    secondary-color: #65BFBD,
    contrast-color: #002328,
    color-text: #002328,
  ),
), corporate), secondary-color);`

Do you have any idea what's wrong with it? Or how we can fix this?

**Comment by Scrum** [comment]
@denniscohn Hi, I will try to understand this problem. Could you write a simple example and put it on a github? Or a little more detailed to describe your example?

**Comment by denniscohn** [comment]
This markup above is messed up I see. Sorry for that.

We set some variables in our _variables.css and using different colors per theme.

$colorset: corporate !default;
$colorsets: (
  corporate: (
    secondary-color: $green-100,
    contrast-color: $white-100,
    color-text: $green-100,
  ),
  ea: (
    secondary-color: $white-100,
    contrast-color: $green-100,
    color-text: $black-100,
  )
)

$theme-colors:       map-get($colorsets, $colorset);
$secondary-color:                     map-get($theme-colors, secondary-color);
$contrast-color:             map-get($theme-colors, contrast-color);
$color-text:                    map-get($theme-colors, color-text);

When I use `background-color: $color-sec` somewhere in my css I expected that would give `$green-100` but it doesn't. it gives me:

`background-color:  map-get(map-get(( corporate: ( secondary-color: #0C8066, contrast-color: #FFFFFF, color-text: #0C8066, ), ea: ( secondary-color: #65BFBD, contrast-color: #002328, color-text: #002328, ), ), corporate), `secondary-color);`

**Comment by Scrum** [comment]
@marcalexiei Hi, I created a test in https://github.com/Scrum/postcss-map-get/tree/milestone-0.2.6 to reproduce this situation, can you implement this support?

**Comment by marcalexiei** [comment]
I'll see what can I do in the next weeks
